export const STAFFS_FETCH_LOADING = 'STAFFS_FETCH_LOADING';
export const STAFFS_FETCH_SUCCESS = 'STAFFS_FETCH_SUCCESS';
export const STAFFS_FETCH_ERROR = 'STAFFS_FETCH_ERROR';
export const DEPARTMENTS_FETCH_LOADING = 'DEPARTMENTS_FETCH_LOADING';
export const DEPARTMENTS_FETCH_SUCCESS = 'DEPARTMENTS_FETCH_SUCCESS';
export const DEPARTMENTS_FETCH_ERROR = 'DEPARTMENTS_FETCH_ERROR';