// fetch Staffs
export const STAFFS_FETCH_LOADING = 'STAFFS_FETCH_LOADING';
export const STAFFS_FETCH_SUCCESS = 'STAFFS_FETCH_SUCCESS';
export const STAFFS_FETCH_ERROR = 'STAFFS_FETCH_ERROR';

// fetch Departments
export const DEPARTMENTS_FETCH_LOADING = 'DEPARTMENTS_FETCH_LOADING';
export const DEPARTMENTS_FETCH_SUCCESS = 'DEPARTMENTS_FETCH_SUCCESS';
export const DEPARTMENTS_FETCH_ERROR = 'DEPARTMENTS_FETCH_ERROR';

// fetch Staffs in a Department
export const STAFFS_IN_DEPT_FETCH_LOADING = 'STAFFS_IN_DEPT_FETCH_LOADING';
export const STAFFS_IN_DEPT_FETCH_SUCCESS = 'STAFFS_IN_DEPT_FETCH_SUCCESS';
export const STAFFS_IN_DEPT_FETCH_ERROR = 'STAFFS_IN_DEPT_FETCH_ERROR';

// fetch Staff's Salaries
export const SALARIES_FETCH_LOADING = 'SALARIES_FETCH_LOADING';
export const SALARIES_FETCH_SUCCESS = 'SALARIES_FETCH_SUCCESS';
export const SALARIES_FETCH_ERROR = 'SALARIES_FETCH_ERROR';

// change staffs to make a new staff list
export const STAFFS_NEW_LIST = "STAFFS_NEW_LIST";

// post Staffs
export const STAFFS_POST_LOADING = 'STAFFS_POST_LOADING';
export const STAFFS_POST_SUCCESS = 'STAFFS_POST_SUCCESS';
export const STAFFS_POST_ERROR = 'STAFFS_POST_ERROR';