export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';
export const STAFF_ADD = 'STAFF_ADD';
export const STAFFS_PRESENT = 'STAFFS_PRESENT';
export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';
export const DEPARTMENT_ADD = 'DEPARTMENTS_ADD';